FROM rust as builder
WORKDIR /app
COPY . .
# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release --bin patwoz-notify

FROM rust as runtime
WORKDIR /app
COPY --from=builder /app/target/release/patwoz-notify /usr/local/bin/patwoz-notify
ENTRYPOINT ["/usr/local/bin/patwoz-notify"]
