FROM rust:bookworm as builder
WORKDIR /app
# RUN cargo install sqlx-cli && sqlx database create && sqlx migrate run

COPY . .
# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release --bin patwoz-notify

FROM rust:bookworm as runtime
WORKDIR /app
COPY --from=builder /app/target/release/patwoz-notify /usr/local/bin/patwoz-notify
ENTRYPOINT ["/usr/local/bin/patwoz-notify"]
